CREATE TABLE contacts (
                          contact_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(100) NOT NULL,
                          email VARCHAR(150) NOT NULL,
                          phone VARCHAR(10) NOT NULL
);